services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shop.entrypoints=websecure"
      - "traefik.http.routers.shop.tls.certResolver=letsencrypt"
      - "traefik.http.routers.shop.rule=Host(`shop.envysartorialist.it`)"
      - "traefik.http.services.shop.loadbalancer.server.port=8080"
    networks:
      - dokploy-network

  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

