services:
  apache:
    image: bitnami/apache:latest
    ports:
      - 8080
    volumes:
      - ./app:/opt/bitnami/apache/htdocs:rw
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shop.entrypoints=websecure"
      - "traefik.http.routers.shop.tls.certResolver=letsencrypt"
      - "traefik.http.routers.shop.rule=Host(`shop.envysartorialist.it`)"
      - "traefik.http.services.shop.loadbalancer.server.port=8080"   
  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - ./app:/opt/bitnami/apache/htdocs:rw 
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
